### ISSUE TITLE
use bending mode forces from lsst-ts/ts_ofc

### ISSUE THREAD

**Issue by bxin** [lsst-ts/ts_phosim#27]
The data files for M1M3 and M2 bending mode forces are needed by both ts_ofc and ts_phosim. 
M1M3_1um_156_force.yaml
M2_1um_force.yaml
To void things getting out of sync, they should only be in one place. We need to remove them from ts_phosim and let ts_phosim use the files in ts_ofc.

**Comment by teweitsai** [comment]
Removed the unused force files in the commit: a7ccafb.
