### ISSUE TITLE
How accurately do the centroids need to be measured

### ISSUE THREAD

**Issue by jbkalmbach** [lsst-ts/ts_phosim#32]

**Comment by teweitsai** [comment]
The algorithm of finding the centroid of donut could be updated in CentroidFindFactory class in lsst-ts/ts_wep package. Another related question is how to find the donut's position on a CCD. The algorithm could be updated in `Utility.searchDonutPos()` of lsst-ts/ts_wep package.

**Comment by jbkalmbach** [comment]
The notebook [centroid_analysis.ipynb](../blob/uw_dev/notebooks/analysis_notebooks/centroid_accuracy.ipynb) in the `uw_dev` branch is updated and has some plots and results we'd like to discuss at tomorrow's AOS meeting.

**Comment by teweitsai** [comment]
I will be on the flight tomorrow and can not attend the AOS meeting.
Please help to add some description to [centroid_analysis.ipynb](../blob/uw_dev/notebooks/analysis_notebooks/centroid_accuracy.ipynb) to improve the readability. I read it and believe I do not really understand what is that analysis for. What are the assumption, experiment design, and conclusion? Please help to explain. Thanks!

**Comment by jbkalmbach** [comment]
Hi Te-Wei, I added some more documentation and a section with some questions we hope to discuss at the telecon today. 

I'll hold off on adding any conclusions until we discuss today with Bo and can see if there are other experiments that would help answer our questions. But if you have time and some insight onto the questions at the end it would be great to hear about that.

**Comment by teweitsai** [comment]
Thank you for the update! I have some comments for the updated centroid_analysis.ipynb.

(1) You do not need to insert code to `WepController.py` to get the donut stamp. The output of `WEPCalculation.calculateWavefrontErrors()` is the list of `SensorWavefrontData`, which has the function of `getListOfDonut()`. The `DonutImage` in the list has the `get` function to get the intra- and extra-focal donut images inherit from `DefocalImage` class.

(2) In this study, you need to consider the donut migration (image forward) in the calculation of wavefront. The process may not have the high resolution (accuracy) to support this study. Please check the code of `CompensableImage._aperture2image()` to see the process. The related coefficient is at `ts_wep/policy/cwfs/instData/lsst (comcam)`.

(3) In the calculation of wavefront error, `ts.wep.cwfs` module will try to find the center of donut images and overlap them. The `CentroidFindFactory` will decide the algorithm to get the center. The `CompensableImage.imageCoCenter()` will try to shift the donut images to have the same center before using the TIE (transport of intensity equation). 

(4) In the study, you will need to consider the affection from (2) and (3). In addition, what will be the affection if you put the `offset` to the TIE and check the calculated wavefront error as a relationship with position offset? Is there any analytical solution to see there is the affection or not?

(5) I do not think it is a good idea to give the conclusion directly based on the numerical solution directly. You could try to do some analysis on TIE first. The confluence page can support the LaTex math in a certain level.

(6) It might be good to have more discussion/ description in centroid_analysis.ipynb. I am not smart enough to fully understand your interesting research based on limited description. Sorry about that.

Thanks!

**Comment by jbkalmbach** [comment]
Based upon discussion with Bo and the latest version of the notebook we are satisfied that the code can find the centroids of the donuts and correctly generate stamps for wavefront sensing. The errors we saw when the test donuts like on the boundary of the amplifier are due to imperfections with ISR so we will open an issue to keep an eye on that. But for now we believe that we will have enough test stars that we can avoid amplifier boundaries in practice.
