### ISSUE TITLE
Stars on Amplifier Boundaries

### ISSUE THREAD

**Issue by jbkalmbach** [lsst-ts/ts_phosim#39]
As described in #32 we noticed that when the donuts used in wavefront sensing lie upon the amplifier boundaries the Zernike errors are increased due to imperfect ISR. This issue is a reminder that the problem exists with the current ISR and to check on this later. In addition, if we have enough test stars in practice to avoid amplifier boundaries we may not have to deal with this issue but will keep this open as a reminder. The plots to show the effects are in https://github.com/lsst-ts/ts_phosim/blob/uw_dev/notebooks/analysis_notebooks/centroid_accuracy.ipynb

**Comment by jbkalmbach** [comment]
Looks like this has been fixed through updates to [phosim_utils](https://github.com/lsst-dm/phosim_utils) and the results can be seen at the end of the notebook @suberlak posted here: https://github.com/lsst-ts/ts_phosim/blob/uw_dev/notebooks/analysis_notebooks/AOS_ISR_baseline.ipynb.

**Comment by teweitsai** [comment]
This fix is not in the master/develop branch of `ts_wep` yet.

**Comment by suberlak** [comment]
Half of the update is live: phosim_utils has been updated on master branch with flipped orientation of flats.  The other half is recommending to use doOverscan ISR option to be  used by ts_wep by default, and that's pending update.

**Comment by suberlak** [comment]
Flats affect this issue much more than the overscan correction though. Overscan corrects for bias in the absence of master bias.
